### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by sychensau** [hillerlab/CESAR2.0#5]
I just tested the mini example of cesar2 according to the recommended steps and found an error reported below. Is this an error for the gb file? Thanks for your attentions.

> Incorrent format
> **'POLR3K	chr16	-	46406	53628	47429	53586	47429-47557,51557-51645,53475-53586' should have minimum 10 fields, found only 8**
> Can't locate Scalar/Util/Numeric.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/csy/Downloads/CESAR2.0/tools/annotateGenesViaCESAR.pl line 8.
> BEGIN failed--compilation aborted at /home/csy/Downloads/CESAR2.0/tools/annotateGenesViaCESAR.pl line 8.
> ./jobListGenePred: line 1: /home/csy/projects/cesarTest/geneAnnotation/echo: No such file or directory
> sed: -e expression #1, char 7: unterminated `s' command
> sed: -e expression #1, char 4: unterminated `s' command
> wrongs # args
>  /home/csy/Downloads/CESAR2.0/tools/bed2GenePred.pl - Convert CESAR2.0 annotated exons (as elements in a bed file) to a genePred file

**Comment by MichaelHiller** [comment]
Hi, 

it seems that you called formatGenePred.pl with twoGenes.gp.forCESAR as input, since the error message comes from this script. 

twoGenes.gp.forCESAR is not a proper genePred format, which formatGenePred.pl would require as input (with 10 fields). Instead twoGenes.gp.forCESAR is the *output* of formatGenePred.pl and can be directly used with annotateGenesViaCESAR.pl. I just copy/pasted the miniExample exactly as is and this works. 

It also seems that you don't have https://metacpan.org/pod/Scalar::Util::Numeric installed. 
Please let me know if problems remain.

Michael
