### ISSUE TITLE
warning message 

### ISSUE THREAD

**Issue by minnndy** [hillerlab/CESAR2.0#6]
Hi, 

I have two questions.

**First**
I ran the CESAR2.0 using CESARTest  you provide ('General workflow of annotating genes in several genomes' part )
but repeated warnings:
WARNING! src/Model.c:254 multi_exon():  Couldn't find declared stop codon in reference 0. (counting from zero)
WARNING! src/Model.c:226 multi_exon():  Couldn't find declared start codon in reference 0. (counting from zero)
WARNING! src/Model.c:226 multi_exon():  Couldn't find declared start codon in reference 0. (counting from zero)
WARNING! src/Model.c:254 multi_exon():  Couldn't find declared stop codon in reference 0. (counting from zero)

I wonder what this warning means.

**Second**
there is a difference in the number of genes(ENST) between genePred result (Results/*.gp) you provided and i tested.
In the case of mm10, 
Results/mm10.gp ENST count : 18601,  geneAnnotation/mm10.gp ENST count : 18600
In the case of falChe1,
Results/falChe1.gp ENST count : 17590, geneAnnotation/falChe1.gp ENST count : 17588
In the case of galGal4,
Results/galGal4.gp ENST count : 17556, geneAnnotation/galGal4.gp ENST count : 17549

so I wonder why this difference is happening. 

Thanks, 
Mindy

**Comment by MichaelHiller** [comment]
Hi Mindy, 

1) This warning says that CESAR2 is expecting a stop codon at the end of the first (0) reference sequence. CESAR2 assumes that this is the last exon, therefore it should have a stop codon if it is complete. Pls try to add the stop to the sequence, then the warning should go away. 

2) I am running the exact same github recipe right now on my machine. Will let you know tomorrow what I find. 
Since you typically have a few genes left, can you pls send me those genes that you seem to miss (Ensembl ID)?
Were there any warnings or errors in your run? Anything related to memory? 

Best, 
Michael

**Comment by minnndy** [comment]
Hi Michael,
 
I checked for differences, but there was a difference in the contents of the gp file generated, not the Ensembl ID.
 

falChe1galGal4mm10
ENST00000394818ENST00000304658ENST00000623152
ENST00000316724ENST00000323116
ENST00000326317
ENST00000326735
ENST00000339560
ENST00000524041
ENST00000623152

 
Below is part of the genePred file.
There's a difference between the Results directory's genePred file and geneAnnotation directory's file.
Unfortunately, no error message occurred during the run.
 
Isn't Results(directory) the result of performing CESAR2.0 with CESARTest?
 
- falChe1 
- galGal4
 
 
Many thanks,
Mindy. 
 
 
-----Original Message-----

**Comment by MichaelHiller** [comment]
Hi Mindy, 

1)
The warnings definitely come from incomplete transcripts that lack start or stop codons. We use all Ensembl transcripts in this example, and some are incomplete. 
For example, ENST00000425250 has no annotated start codon (UCSC genome browser hg38: chr6_GL000256v2_alt:3,190,762-3,190,887).
ENST00000553001 has no annotated stop codon (hg38 chr21:32,578,811-32,578,858).

Nothing to worry about. 

2)
Yes, the Results dir has the final results of CESARTest. 

After re-running, I get the same number of genes as you do:
   17588 falChe1.gp
   17549 galGal4.gp
   18600 mm10.gp
   18880 oryAfe1.gp

The few differences come from transcripts with 0 length, which are artifacts. We introduced a filter for such transcripts. Other minor changes in transcript mapping seem to refer to differences in the first or last exon, which is due to code changes in CESAR2. But apparently the files in the Results directory were not updated, which I have done now. 

So, overall, it seems to work for you as you get the same (new) results. 
Best,
Michael

**Comment by ghost** [comment]
hi;
i'm miaomiaoHuang from wuhan university.I want to use CESAR to observe if exons has changed by  aligning human and other species gene,but,i don`t understand how to use it for my style.i see your examples,but,it confused me.so can you help me ?just tell me the step to set. the reference gene is human gene,i want to check if the same gene' exons  has changed  in other species.thanks!

**Comment by MichaelHiller** [comment]
Hi, 
well you could just download the human Ensembl or GenCode annotation (genePred format) directly from the UCSC genome browser, extract your human gene of interest, and then run the code examples that we have provided. 
Best
Michael

**Comment by ghost** [comment]
hi;
thanks for your help,i'll do it best!
best wishes to you! 
| |
黄苗苗
|
|
huangmioamiao@163.com
|
签名由网易邮箱大师定制
On 3/2/2019 16:23，Michael Hiller<notifications@github.com> wrote：

Hi,
well you could just download the human Ensembl or GenCode annotation (genePred format) directly from the UCSC genome browser, extract your human gene of interest, and then run the code examples that we have provided.
Best
Michael

**Comment by ghost** [comment]
hi'
i have a question.i use my file and run CESAR,but,it has no result,nothing.no warning,no result.i don't know what happened.will you help me ?

**Comment by MichaelHiller** [comment]
Is the input file format correct (similar to our examples except the sequence of course)?
If yes, pls send me your input file and how you call cesar.

**Comment by ghost** [comment]
i solve this problem. loss '>' in file.


| |
黄苗苗
|
|
huangmioamiao@163.com
|
签名由网易邮箱大师定制
On 3/29/2019 14:37，Michael Hiller<notifications@github.com> wrote：

Is the input file format correct (similar to our examples except the sequence of course)?
If yes, pls send me your input file and how you call cesar.
